In [10]:
import numpy as np

In [12]:
#As different columns have different datatypes in the data, we use the below approach

In [13]:
dtype = [('data','U10'),('temperature', 'f4'),('precipitation', 'f4'), ('wind_speed', 'f4')]

In [14]:
data = np.genfromtxt('weather_data.csv', delimiter=',',skip_header=True, dtype=dtype)

In [15]:
data

array([('1/1/21', 5.6, 0. , 15.2), ('1/2/21', 4.8, 0.2, 12.8),
       ('1/3/21', 6.1, 5.3,  9.6), ('1/4/21', 7.4, 1. ,  8.4),
       ('1/5/21', 6.8, 0. , 10. ), ('1/6/21', 3.2, 2.1,  5.8),
       ('1/7/21', 4.1, 0. , 11. ), ('1/8/21', 5.5, 0. , 12.5),
       ('1/9/21', 6. , 3.6, 14.2), ('1/10/21', 5.8, 0. , 13.1),
       ('1/11/21', 2.8, 0.5,  7.4), ('1/12/21', 3.1, 0. ,  6.2),
       ('1/13/21', 4.9, 1.2,  9.3), ('1/14/21', 6.7, 4.3, 11.9),
       ('1/15/21', 7.3, 0. , 14.5), ('1/16/21', 8.1, 0. , 15.8),
       ('1/17/21', 6.4, 2.4, 10.2), ('1/18/21', 5.2, 1.5,  8.9),
       ('1/19/21', 4.6, 0. ,  9.7), ('1/20/21', 5.9, 0. , 12. ),
       ('1/21/21', 7. , 3.2, 14.6), ('1/22/21', 8.3, 0. , 16.1),
       ('1/23/21', 7.5, 0. , 13.8), ('1/24/21', 6.9, 1.8, 12.2),
       ('1/25/21', 5.4, 0. , 10.4), ('1/26/21', 4.2, 0. ,  9.5),
       ('1/27/21', 3.6, 0.7,  7.1), ('1/28/21', 2.9, 0. ,  6.8),
       ('1/29/21', 3.5, 1.1,  8.3), ('1/30/21', 4.7, 0. ,  9.9),
       ('1/31/21', 6. , 0. , 11.7)

In [16]:
#Statistical Analysis

In [17]:
#calculating mean of temp,precip and wind_speed

In [21]:
temp_mean = np.mean(data['temperature'])
precip_mean = np.mean(data['precipitation'])
wind_mean = np.mean(data['wind_speed'])

In [26]:
wmeans = np.array([temp_mean, precip_mean, wind_mean])
wmeans

array([ 5.493548 ,  0.9322581, 10.932258 ], dtype=float32)

In [27]:
#calculating median of temp,precip and wind_speed

In [28]:
temp_median = np.median(data['temperature'])
precip_median = np.median(data['precipitation'])
wind_median = np.median(data['wind_speed'])

In [29]:
wmedians = np.array([temp_median, precip_median,wind_median])
wmedians

array([ 5.6,  0. , 10.4], dtype=float32)

In [30]:
#calculating standard deviation of temp,precip and wind_speed

In [31]:
temp_sd = np.std(data['temperature'])
precip_sd = np.std(data['precipitation'])
wind_sd = np.std(data['wind_speed'])

In [32]:
wstds = np.array([temp_sd,precip_sd,wind_sd])
wstds

array([1.5395716, 1.4247552, 2.8388305], dtype=float32)

In [33]:
#determining highest and lowest temperature recorded with dates

In [47]:
data

array([('1/1/21', 5.6, 0. , 15.2), ('1/2/21', 4.8, 0.2, 12.8),
       ('1/3/21', 6.1, 5.3,  9.6), ('1/4/21', 7.4, 1. ,  8.4),
       ('1/5/21', 6.8, 0. , 10. ), ('1/6/21', 3.2, 2.1,  5.8),
       ('1/7/21', 4.1, 0. , 11. ), ('1/8/21', 5.5, 0. , 12.5),
       ('1/9/21', 6. , 3.6, 14.2), ('1/10/21', 5.8, 0. , 13.1),
       ('1/11/21', 2.8, 0.5,  7.4), ('1/12/21', 3.1, 0. ,  6.2),
       ('1/13/21', 4.9, 1.2,  9.3), ('1/14/21', 6.7, 4.3, 11.9),
       ('1/15/21', 7.3, 0. , 14.5), ('1/16/21', 8.1, 0. , 15.8),
       ('1/17/21', 6.4, 2.4, 10.2), ('1/18/21', 5.2, 1.5,  8.9),
       ('1/19/21', 4.6, 0. ,  9.7), ('1/20/21', 5.9, 0. , 12. ),
       ('1/21/21', 7. , 3.2, 14.6), ('1/22/21', 8.3, 0. , 16.1),
       ('1/23/21', 7.5, 0. , 13.8), ('1/24/21', 6.9, 1.8, 12.2),
       ('1/25/21', 5.4, 0. , 10.4), ('1/26/21', 4.2, 0. ,  9.5),
       ('1/27/21', 3.6, 0.7,  7.1), ('1/28/21', 2.9, 0. ,  6.8),
       ('1/29/21', 3.5, 1.1,  8.3), ('1/30/21', 4.7, 0. ,  9.9),
       ('1/31/21', 6. , 0. , 11.7)

In [48]:
#getting the date of day of lowest temperature and highest temperature 

In [71]:
lowtemp_date = data[data['temperature'] == np.min(data['temperature'])]

In [123]:
lowtemp_date[0][0]

'1/11/21'

In [124]:
hightemp_date = data[data['temperature'] == np.max(data['temperature'])]

In [128]:
hightemp_date['data'][0]

'1/22/21'

In [90]:
#Find the days with precipitation greater than a certain threshold (e.g., 10 mm) and count how many such days there are.

In [130]:
high_precip_days = data[data['precipitation'] > 0.1]['data']

In [139]:
x = list(high_precip_days[:])
num_of_days = len(x)
num_of_days

14

In [140]:
#Identify the month with the highest average wind speed.

In [141]:
highw_date = data[data['wind_speed'] == np.max(data['wind_speed'])]

In [149]:
date_str = str(highw_date[0][0])

In [153]:
x = date_str.split('/')

In [156]:
match int(x[0]):
    case 1: 
        month = 'Jan'
    case 2:
        month = 'Feb'
    
month

'Jan'